# Generated by Django 6.0.4 on 2026-04-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('equipment_type', models.CharField(max_length=255, verbose_name='Type')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Fabricant')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Référence')),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('status', models.CharField(choices=[('En service', 'En service'), ('En panne', 'En panne'), ('En maintenance', 'En maintenance'), ('Hors service', 'Hors service')], default='En service', max_length=50, verbose_name='Statut')),
                ('criticality', models.CharField(choices=[('Très élevée', 'Très élevée'), ('Élevée', 'Élevée'), ('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Faible', 'Faible')], default='Moyenne', max_length=50, verbose_name='Criticité')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['name', 'code'],
            },
        ),
    ]
