# Generated by Django 6.0.4 on 2026-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_clean_locations'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['status'], name='equipment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['location'], name='equipment_location_idx'),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['criticality'], name='equipment_criticality_idx'),
        ),
    ]
