# Generated by Django 6.0.4 on 2026-04-29 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('criticality', models.CharField(choices=[('Très élevée', 'Très élevée'), ('Élevée', 'Élevée'), ('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Faible', 'Faible')], default='Moyenne', max_length=50)),
                ('priority', models.CharField(choices=[('Urgente', 'Urgente'), ('Normale', 'Normale'), ('Faible', 'Faible')], default='Normale', max_length=20)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Résolue', 'Résolue')], default='En attente', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Pannes',
                'ordering': ['-reported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('intervention_type', models.CharField(choices=[('Corrective', 'Corrective'), ('Préventive', 'Préventive')], default='Corrective', max_length=20)),
                ('priority', models.CharField(choices=[('Urgente', 'Urgente'), ('Normale', 'Normale'), ('Faible', 'Faible')], default='Normale', max_length=20)),
                ('status', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='En cours', max_length=20)),
                ('description', models.TextField()),
                ('report', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('equipment_status_after', models.CharField(blank=True, choices=[('En service', 'En service'), ('En panne', 'En panne'), ('En maintenance', 'En maintenance'), ('Hors service', 'Hors service')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
