# Generated by Django 6.0.4 on 2026-05-05 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipement_equipment_status_idx_and_more'),
        ('maintenance', '0004_data_migration_update_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name'], name='audit_model_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incident_status_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['reported_at'], name='incident_reported_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['operator'], name='incident_operator_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['technician'], name='incident_technician_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['equipment'], name='incident_equipment_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['status'], name='intervention_status_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['start_date'], name='intervention_start_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['technician'], name='intervention_tech_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['equipment'], name='intervention_equipment_idx'),
        ),
    ]
